[default]
address = "127.0.0.1"
port = 8000
log_level = "normal"

[debug.tls]
certs = "tls/localhost.pem"
key = "tls/localhost.key" 

[e2e]
port = 8001

[release]
address = "0.0.0.0"
port = 8086
log_level = "critical"
secret_key = "Wa9qn3ctYXz31yOa9MGXkoADJMio24XyTVKgJhvi9H8="
