[development]
address = "localhost"
port = 8000
log = "normal"
tls = { certs = "tls/localhost.pem", key = "tls/localhost.key" }

[staging]
address = "localhost"
port = 8001
log = "normal"

[production]
address = "0.0.0.0"
port = 8086
log = "critical"
secret_key = "Wa9qn3ctYXz31yOa9MGXkoADJMio24XyTVKgJhvi9H8="
